### ISSUE TITLE
Exception with some resources inside the file

### ISSUE THREAD

**Issue by vincenzopalazzo** [KrishnaMoorthy12/trident#34]
Hi @KrishnaMoorthy12,

Thanks for using my library :) your project is very cool.

I'm training to run the project in my ide and I have a reception during the following use case:

Setting -> Conf. -> Save

<details>
<summary>This is the  exception</summary>
<br>
Exception
<br><br>
<pre>

```
/usr/lib/jvm/jdk-13.0.2/bin/java -javaagent:/home/vincent/.program/idea-IU-193.5662.53/lib/idea_rt.jar=44607:/home/vincent/.program/idea-IU-193.5662.53/bin -Dfile.encoding=UTF-8 -classpath /home/vincent/Github/trident/target/classes:/home/vincent/.m2/repository/io/github/vincenzopalazzo/material-ui-swing/1.1.1_pre-release_6.1/material-ui-swing-1.1.1_pre-release_6.1.jar:/home/vincent/.m2/repository/org/swinglabs/swingx/1.6.1/swingx-1.6.1.jar:/home/vincent/.m2/repository/com/jhlabs/filters/2.0.235/filters-2.0.235.jar:/home/vincent/.m2/repository/org/swinglabs/swing-worker/1.1/swing-worker-1.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-bundle/1.4.0/jiconfont-bundle-1.4.0.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-font_awesome/4.7.0.1/jiconfont-font_awesome-4.7.0.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-open_iconic/1.1.1.3/jiconfont-open_iconic-1.1.1.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-elusive/2.0.3/jiconfont-elusive-2.0.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-entypo/2.0.3/jiconfont-entypo-2.0.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-typicons/2.0.7.1/jiconfont-typicons-2.0.7.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-swing/1.0.1/jiconfont-swing-1.0.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont/1.0.0/jiconfont-1.0.0.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-google_material_design_icons/2.2.0.2/jiconfont-google_material_design_icons-2.2.0.2.jar Trident
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Configurations.write(Configurations.java:426)
	at ConfigurationsListener.actionPerformed(Configurations.java:526)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1024)
	at Trident.writeLog(Trident.java:149)
	at Trident.ErrorDialog(Trident.java:118)
	at FileMenuListener.actionPerformed(FileMenuListener.java:373)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</pre>
</details>

Also, I want to ask, you are some ideas to introduce the syntax highlights?

I'm Dyslexic and this font [OpenDyslexia](https://opendyslexic.org/) helps me.

You load the font only from the system or you can load the font also to the repository?

**Comment by krissh-codes** [comment]
Hi again! Using your preferred font is very very easy in Trident. Just install the font you like to your system and you're good to go. You'll find the font listed in the font dd list box in the configuration dialog.

**Comment by vincenzopalazzo** [comment]
@KrishnaMoorthy12 I will try it, thanks.

About the exception, what do you think?

**Comment by krissh-codes** [comment]
> About the exception, what do you think?
> 
I'll check it out. Can you send me the log file?

**Comment by krissh-codes** [comment]
Syntax highlighting is still far from reach. I tried some methods.. but I gave up very early. I'll try to make it possible. But it won't probably make it in the next build.

**Comment by vincenzopalazzo** [comment]
@KrishnaMoorthy12 

>I'll check it out. Can you send me the log file?

Where can I find the log file?

>Syntax highlighting is still far from reach. I tried some methods.. but I gave up very early. I'll try to make it possible. But it won't probably make it in the next build.

The Syntax highlighting is still far from reach is a very cool proof :)

**Comment by KrishnaMoorthy12** [comment]
Inside logs directory

**Comment by krissh-codes** [comment]
> 
> Where can I find the log file?

Inside logs folder

> The Syntax highlighting is still far from reach is a very cool proof :)

I don't understand. Not very good at English (I don't understand slangs etc..)

**Comment by vincenzopalazzo** [comment]
@KrishnaMoorthy12 

> Inside logs folder

I don't found the directory sorry

>I don't understand. Not very good at English (I don't understand slangs etc..)

Sorry, I'm learning English, so I think is very difficult implement this function with the normal Swing component :)
